### ISSUE TITLE
Issue with Web3JS v^1.9.0

### ISSUE THREAD

**Issue by subhasishgoswami** [fireblocks/fireblocks-web3-provider#16]
Hey team,

I was recently trying to use the provider with Web3js v1.9.0 but it keeps giving an error- `Provider does not have a request or send method to use`.
While it works perfectly with Web3js v4, wanted to understand if it is possible to use the provider with v1.9.0 as well.

**Error**
<img width="726" alt="Screenshot 2023-11-08 at 3 01 18 PM" src="https://github.com/fireblocks/fireblocks-web3-provider/assets/43542047/e317787b-1369-43af-b10b-a22123ebbf60">

**Dependencies**
node version: v16.20.0
npm version: 8.19.4
web3: ^1.9.0
@fireblocks/fireblocks-web3-provider: ^1.2.3

**Comment by orenyomtov** [comment]
It should actually work because the [FireblocksWeb3Provider](https://github.com/fireblocks/fireblocks-web3-provider/blob/main/src/provider.ts) has both `send` and `request` methods
