### ISSUE TITLE
I should get 3.0 but i am getting 1.0 

### ISSUE THREAD

**Issue by shahidkhan142** [fireblocks/fireblocks-web3-provider#23]
``` 
const eip1193Provider = new FireblocksWeb3Provider({
      privateKey: apiSecret,
      apiKey: apiKey,
      vaultAccountIds: this.arg.vaultId,
      chainId: ChainId.BSC,
    });
```
    
    
``` 
var gasPriceRaw = await this.provider.getGasPrice();
    var gasPrice = ethers.utils.formatUnits(gasPriceRaw, "gwei");
    gasPrice = gasPrice;
```
![Screenshot 2024-03-25 at 6 34 56 AM](https://github.com/fireblocks/fireblocks-web3-provider/assets/127819741/abbcbf64-687d-453a-a320-7cb9d3b38c21)

**Comment by orenyomtov** [comment]
Try specifying your own rpcUrl where you know it returns the right answer

**Comment by shahidkhan142** [comment]
> Try specifying your own rpcUrl where you know it returns the right answer

How can i define own rpcUrl

**Comment by orenyomtov** [comment]
In the config object as documented in the readme
